package com.example.socialmedia.ui.utils

object Constants {
    val TOKEN_KEY = "token"
    var googlecode = 234
    val delay_2000 = 2000L
    val INDEX_0 = 0
    val INDEX_1 = 1
    val INDEX_2 = 2
    const val INDEX_3 = 3
    const val INDEX_4 = 4
    const val KEY_IN_DEX = "KEY_IN_DEX"
    const val ITEM_HOME = "home"
    const val CAMERA = "camera"
    const val KEY_CHAT_ID = "id"
    const val KEY_SENDER_ID = "senderId"
    const val KEY_RECEIVER_ID = "receiverId"
    const val KEY_TYPE_MESSAGE = "typeMessage"
    const val KEY_TIMESTAMP = "timestamp"
    const val KEY_MESSAGE = "message"
    const val KEY_DURATION = "duration"
    const val KEY_SEEN_STATE = "seen"
    const val KEY_IS_MUTE_SEND = "muteSend"
    const val KEY_IS_MUTE_RECEIVER = "muteReversion"
    const val KEY_COLLECT_CHAT_ROOMS = "chatRooms"
    const val KEY_COLLECT_CHAT_MESSAGE = "message"
    const val KEY_LIST_USER = "listUid"
    const val KEY_LAST_MESS_SENDER_ID = "lastMessageSenderId"
    const val KEY_LAST_MESS_TIMESTAMP = "lastMessageTimestamp"
    const val KEY_LAST_MESSAGE = "lastMessage"
    const val TYPE_LAST_MESSAGE_IMAGE = "send 1 image"
    const val TYPE_LAST_MESSAGE_VIDEO = "send 1 video"
    const val TYPE_LAST_MESSAGE_AUDIO = "send 1 audio"
    const val KEY_USER_ID = "id"
    const val KEY_STATUS = "status"
    const val KEY_LIST_BLOCK = "listBlock"
    const val KEY_STATUS_ONLINE = "Online"
    const val KEY_STATUS_OFFLINE = "Offline"
    const val KEY_STATUS_TYPING = "Typing..."
    const val KEY_USER_NAME = "name"
    const val KEY_USER_AVATAR = "avtPath"
    const val KEY_STATE_ONLINE = "Online"
    const val KEY_FOLLOW = "Follow"
    const val KEY_FOLLOWING = "Following"
    const val KEY_FOLLOWERS = "Followers"
    const val KEY_TYPE = "type"
    const val KEY_USERID = "uid"
    const val KEY_CHECKBOX = "KEY_CHECKBOX"
    const val KEY_PROFILE = "KEY_PROFILE"
    const val KEY_BLOCK = "Block"
    const val KEY_UN_BLOCK = "Unblock"
    const val KEY_ITEM_HOME = "KEY_ITEM_HOME"
    const val KEY_COLLECTION_USER = "Users"
    const val IMAGE = "image"
    const val VIDEO = "video"
    const val AUDIO = "audio"
    const val TEXT = "text"
    const val REQUEST_CODE_GET_IMAGE_FROM_GALLERY = 201
    const val REQUEST_CODE_RECORD_AUDIO = 202
    const val REQUEST_CODE_TAKE_PHOTO_FROM_CAMERA = 203
    const val REQUEST_CODE_OPEN_SETTING = 204
    const val KEY_CONVERSION_ID = "conversionId"
  const val KEY_5_COIN = "Com.SocialMedia.pack_1" // 5 coin
  const val KEY_10_COIN = "Com.SocialMedia.pack_2" // 100 coin
  const val KEY_20_COIN = "Com.SocialMedia.pack_3" // 150 coin
  const val KEY_50_COIN = "Com.SocialMedia.pack_4" // 300 coin
  const val KEY_100_COIN = "Com.SocialMedia.pack_5" // 500 coin
  const val KEY_150_COIN = "Com.SocialMedia.pack_6" // 700 coin
  const val KEY_200_COIN = "Com.SocialMedia.pack_7" // 999 coin
  const val KEY_300_COIN = "Com.SocialMedia.pack_8"

    const val KEY_LIST_HISTORY_SEARCH = "listUserSearch"
    const val KEY_LIST_UID_NEED_MUTE = "listUidNeedMute"
}